[package]
name = "schmfy"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Schmfication library"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
