[package]
name = "schmfy"
version = "0.2.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Schmfication library"
readme = "README.md"
repository = "https://git.flueren.eu/JonOfUs/Schmfy"
documentation = "https://docs.rs/schmfy"

[dependencies]
